[package]
name = "librustzcash"
version = "0.1.0"
authors = ["Sean Bowe <ewillbefull@gmail.com>"]

[lib]
name = "rustzcash"
path = "src/rustzcash.rs"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2"
pairing = "0.14.2"
lazy_static = "1"
bellman = "0.1"
byteorder = "1"
rand = "0.4"

[dependencies.sapling-crypto]
git = "https://github.com/zcash-hackworks/sapling-crypto"
rev = "eb409fa3cf8df215ae8d35f5e385751a0c5ffb85"

[profile.release]
lto = true
panic = 'abort'
codegen-units = 1
