[package]
name = "librustzcash"
version = "0.1.0"
authors = ["Sean Bowe <ewillbefull@gmail.com>"]

[lib]
name = "rustzcash"
path = "src/rustzcash.rs"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2"

[dependencies.sapling-crypto]
git = "https://github.com/zcash-hackworks/sapling-crypto"
rev = "e554b473dd10885d232f42237c13282f5b6fee43"
