[package]
name = "zip32"
version = "0.0.0"
authors = [
    "Jack Grigg <jack@z.cash>",
]
license = "MIT/Apache-2.0"

description = "Library for implementing shielded hierarchical deterministic wallets"
documentation = "https://docs.rs/zip32/"
homepage = "https://github.com/zcash-hackworks/zip32"
repository = "https://github.com/zcash-hackworks/zip32"

[dependencies]
pairing = "0.14.2"

[dependencies.sapling-crypto]
git = "https://github.com/zcash-hackworks/sapling-crypto"
rev = "21084bde2019c04bd34208e63c3560fe2c02fb0e"
