[package]
name = "librustzcash"
version = "0.1.0"
authors = ["Sean Bowe <ewillbefull@gmail.com>"]

[lib]
name = "rustzcash"
path = "src/rustzcash.rs"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2"
pairing = "0.14.1"
lazy_static = "1"
bellman = "0.1"
byteorder = "1"
rand = "0.4"

[dependencies.sapling-crypto]
git = "https://github.com/zcash-hackworks/sapling-crypto"
rev = "7beeb52730e24724ee10ea2458ecf7776cb59c58"

[profile.release]
lto = true
panic = 'abort'
